# Generated by Django 2.2.3 on 2019-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='date',
            new_name='start_date',
        ),
    ]
