# Generated by Django 2.2.3 on 2019-08-11 16:43

from django.db import migrations, models
import django.db.models.deletion
import ui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('readable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siri.Readable')),
                ('image', models.ImageField(upload_to='projects/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            bases=('siri.readable', ui.models.Renderable),
        ),
    ]
