# Generated by Django 2.2.3 on 2019-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20190811_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
