# Generated by Django 2.2.3 on 2019-08-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20190811_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='image',
            new_name='file',
        ),
    ]
