# Generated by Django 2.2.3 on 2019-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20190811_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.FileField(upload_to='artworks/'),
        ),
    ]
