# Generated by Django 2.2.3 on 2019-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readable',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
