# Generated by Django 2.2.3 on 2019-08-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_css',
        ),
    ]
