# Generated by Django 2.2.3 on 2019-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_icon_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='thumbnail',
        ),
    ]
