# Generated by Django 2.2.3 on 2019-08-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['title']},
        ),
    ]
